### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by fsimkovic** [sauloho/Flib#2]
Running the pipeline.sh script works until the following line gets executed:

```
$FLIB/Flib $OUTPUT $PDB > $OUTPUT.lib3000 2> $OUTPUT.log
```

The output printed to `$OUTPUT.lib3000` is the `Usage: /home/felix/opt/Flib/Flib PDB_CODE`. The problem seems to have been introduced with commit 27d92fe.

**Comment by sauloho** [comment]
My apologies, Felix.  The issue may have arised because I changed the way you evoke the pipeline script.

Usage was changed from:

`echo "PDB_ID" | $Flib/pipeline.sh`

To:

`$Flib/pipeline.sh PDB_ID`

The later seems to work on my current version of the code, while the former seems to raise the issue you mentioned.

The other potential cause of this issue could be that the variable $PDB (which points to your installation of the PDB) was not set up/exported correctly.

Could you confirm that you are running the pipeline.sh script correctly and that the variable $PDB was exported correctly?

**Comment by fsimkovic** [comment]
I think the problem is in this command

```
$FLIB/Flib $OUTPUT $PDB > $OUTPUT.lib3000 2> $OUTPUT.log
```

Basically, you have introduced the `$PDB` variable which in fact is not needed. When removing it, Flib works fine.

**Comment by sauloho** [comment]
I will make sure to remove the variable from that command on the master branch then. Thank you for spotting the inconsistency.
